//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetListAppointmentForAdminCount_Result
    {
        public Nullable<int> TotalResult { get; set; }
        public Nullable<int> TotalNotClaimed { get; set; }
        public Nullable<int> TotalClaimed { get; set; }
        public Nullable<int> TotalPayed { get; set; }
        public Nullable<int> TotalForthcoming { get; set; }
        public Nullable<int> TotalCompleted { get; set; }
        public Nullable<int> TotalCanceledWithCharge { get; set; }
        public Nullable<int> TotalCanceledWithoutCharge { get; set; }
        public Nullable<int> TotalPresenceToConfirm { get; set; }
    }
}
