//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAppointment()
        {
            this.ClientPaymentInfos = new HashSet<ClientPaymentInfo>();
        }
    
        public int Id { get; set; }
        public int TherapistId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public decimal NbSession { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int NatureActId { get; set; }
        public int ConsultationTypeId { get; set; }
        public Nullable<int> RepetitionId { get; set; }
        public int AppointmentStatusId { get; set; }
        public Nullable<int> TherapistBillId { get; set; }
        public Nullable<int> ClientPaymentReceiptNumber { get; set; }
        public Nullable<decimal> TotalDollarAmount { get; set; }
        public Nullable<System.DateTime> ClientPaymentDate { get; set; }
        public Nullable<System.Guid> PaymentUrlCode { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ReasonDeleteClientAppointmentId { get; set; }
        public Nullable<System.DateTime> ReferenceStartDateTime { get; set; }
        public bool IsRemeinderEmailSent { get; set; }
        public Nullable<System.DateTime> ClientBillGeneratedDate { get; set; }
        public int ProfessionalTitleId { get; set; }
    
        public virtual AppointmentStatu AppointmentStatu { get; set; }
        public virtual ClientAppointmentRepetition ClientAppointmentRepetition { get; set; }
        public virtual ConsultationType ConsultationType { get; set; }
        public virtual NatureAct NatureAct { get; set; }
        public virtual ReasonsDeleteClientAppointment ReasonsDeleteClientAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPaymentInfo> ClientPaymentInfos { get; set; }
        public virtual Therapist Therapist { get; set; }
        public virtual ProfessionalTitle ProfessionalTitles { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
