//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalClientFee
    {
        public int Id { get; set; }
        public decimal ExternalClientPercentageFeeDecimal { get; set; }
        public decimal ExternalClientFixedFee { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
