//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAssociationClientsSent
    {
        public int Id { get; set; }
        public int ExternalAssociationId { get; set; }
        public int ClientId { get; set; }
        public int ExternalAssociationClientSentStatusId { get; set; }
        public System.DateTime SentToAssociationDate { get; set; }
        public System.DateTime StatusChangedDate { get; set; }
    
        public virtual ExternalAssociationClientSentStatu ExternalAssociationClientSentStatu { get; set; }
        public virtual ExternalAssociation ExternalAssociation { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
