//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferedService_OfferedServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferedService_OfferedServiceType()
        {
            this.TherapistOfferedServices = new HashSet<TherapistOfferedService>();
        }
    
        public int Id { get; set; }
        public int OfferedServiceId { get; set; }
        public int OfferedServiceTypeId { get; set; }
    
        public virtual OfferedServiceType OfferedServiceType { get; set; }
        public virtual OfferedService OfferedService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistOfferedService> TherapistOfferedServices { get; set; }
    }
}
