//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessionalTitle()
        {
            this.TherapistProfessionalTitles = new HashSet<TherapistProfessionalTitle>();
            this.ClientAppointments = new HashSet<ClientAppointments>();
        }
    
        public int Id { get; set; }
        public string ProfessionalTitle1 { get; set; }
        public string ProfessionalTitleEN { get; set; }
        public string Secteur { get; set; }
        public string SecteurEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistProfessionalTitle> TherapistProfessionalTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAppointments> ClientAppointments { get; set; }
    }
}
