//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseauPsyInfo
    {
        public int Id { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TpsNumber { get; set; }
        public string TvqNumber { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string RegionAbbreviation { get; set; }
        public string PostalCode { get; set; }
    }
}
