//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapistPayInformations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TherapistPayInformations()
        {
            this.ClientAppointments = new HashSet<ClientAppointments>();
        }
    
        public int Id { get; set; }
        public int TherapistId { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public decimal TherapistHourlyWage { get; set; }
        public decimal ClientHourlyCost { get; set; }
        public bool IsTaxable { get; set; }
        public string PayInfoName { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAppointments> ClientAppointments { get; set; }
        public virtual Therapist Therapists { get; set; }
    }
}
