//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapistInfo
    {
        public int Id { get; set; }
        public int TherapistId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AccreditationId { get; set; }
        public string OpqNumber { get; set; }
        public string CertificationAndSpecialities { get; set; }
        public Nullable<bool> TakeClientFromAssuranceCompany { get; set; }
        public Nullable<bool> TakeClientFromThirdPartyPayer { get; set; }
        public Nullable<bool> IsInterestedForFormation { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string TpsNumber { get; set; }
        public string TvqNumber { get; set; }
    
        public virtual Accreditation Accreditations { get; set; }
        public virtual Accreditation Accreditations1 { get; set; }
        public virtual Gender Genders { get; set; }
        public virtual Region Regions { get; set; }
        public virtual Therapist Therapists { get; set; }
    }
}
