//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetListClientRequestWaitingForTherapist_Result
    {
        public int RequestId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public System.DateTime RequestSentDate { get; set; }
        public string Region { get; set; }
        public string ConsultationReason { get; set; }
        public string Message { get; set; }
        public string AdditionalMessageFromAdmin { get; set; }
        public string ClientName { get; set; }
    }
}
