//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ClientAvailabilities = new HashSet<ClientAvailability>();
            this.ClientConsultationTypes = new HashSet<ClientConsultationType>();
            this.ClientInfo = new HashSet<ClientInfo>();
            this.ClientLanguage = new HashSet<ClientLanguage>();
            this.ExternalAssociationClientsSent = new HashSet<ExternalAssociationClientsSent>();
            this.TherapistClientRequest = new HashSet<TherapistClientRequest>();
            this.ClientAppointments = new HashSet<ClientAppointments>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TherapistId { get; set; }
        public int LanguageId { get; set; }
        public int ConsultationReasonId { get; set; }
        public int ClientAgeRangeId { get; set; }
        public string Message { get; set; }
        public System.DateTime RequestDate { get; set; }
        public bool IsExternalClient { get; set; }
        public Nullable<int> ExternalAssociationId { get; set; }
        public Nullable<int> ReasonDeleteClientRequestId { get; set; }
        public string DeletedAdditionalNotes { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAvailability> ClientAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientConsultationType> ClientConsultationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientInfo> ClientInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLanguage> ClientLanguage { get; set; }
        public virtual ClientsAgeRange ClientsAgeRange { get; set; }
        public virtual ConsultationReason ConsultationReasons { get; set; }
        public virtual ExternalAssociation ExternalAssociations { get; set; }
        public virtual ReasonsDeleteClientRequest ReasonsDeleteClientRequest { get; set; }
        public virtual Language Languages { get; set; }
        public virtual Therapist Therapists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalAssociationClientsSent> ExternalAssociationClientsSent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistClientRequest> TherapistClientRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAppointments> ClientAppointments { get; set; }
    }
}
