//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPaymentInfo
    {
        public int Id { get; set; }
        public int ClientAppointmentId { get; set; }
        public int OrderId { get; set; }
        public string UniqueRef { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseText { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string AvsResponse { get; set; }
        public string CvvResponse { get; set; }
        public bool DidSucceed { get; set; }
        public string ResponseBody { get; set; }
    
        public virtual ClientAppointments ClientAppointments { get; set; }
    }
}
