//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAppointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAppointments()
        {
            this.ClientPaymentInfos = new HashSet<ClientPaymentInfo>();
        }
    
        public int Id { get; set; }
        public int TherapistId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public decimal NbSession { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int NatureActId { get; set; }
        public int ProfessionalTitleId { get; set; }
        public int ConsultationTypeId { get; set; }
        public Nullable<int> RepetitionId { get; set; }
        public int AppointmentStatusId { get; set; }
        public Nullable<int> TherapistBillId { get; set; }
        public Nullable<int> ClientPaymentReceiptNumber { get; set; }
        public Nullable<decimal> TotalDollarAmount { get; set; }
        public Nullable<System.DateTime> ClientPaymentDate { get; set; }
        public Nullable<System.Guid> PaymentUrlCode { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ReasonDeleteClientAppointmentId { get; set; }
        public Nullable<System.DateTime> ReferenceStartDateTime { get; set; }
        public bool IsRemeinderEmailSent { get; set; }
        public Nullable<System.DateTime> ClientBillGeneratedDate { get; set; }
        public Nullable<int> TherapistPayInformationId { get; set; }
    
        public virtual AppointmentStatu AppointmentStatus { get; set; }
        public virtual ClientAppointmentRepetition ClientAppointmentRepetition { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ConsultationType ConsultationTypes { get; set; }
        public virtual NatureAct NatureActs { get; set; }
        public virtual ProfessionalTitle ProfessionalTitles { get; set; }
        public virtual ReasonsDeleteClientAppointment ReasonsDeleteClientAppointment { get; set; }
        public virtual Therapist Therapists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPaymentInfo> ClientPaymentInfos { get; set; }
        public virtual TherapistPayInformations TherapistPayInformations { get; set; }
    }
}
