//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfo
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public int RegionId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<decimal> TherapistHourlyWage { get; set; }
        public Nullable<decimal> ClientHourlyCost { get; set; }
        public int GenderId { get; set; }
    
        public virtual Region Regions { get; set; }
        public virtual Gender Genders { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
