//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetClientSentToExternalAssociation_Result
    {
        public int ExternalAssociationClientSentId { get; set; }
        public string AssociationName { get; set; }
        public System.DateTime SentToAssociationDate { get; set; }
        public System.DateTime StatusChangedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ClientName { get; set; }
        public string Status { get; set; }
    }
}
