//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasOfPractice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreasOfPractice()
        {
            this.TherapistAreaOfPractices = new HashSet<TherapistAreaOfPractice>();
        }
    
        public int Id { get; set; }
        public string AreaOfPractice { get; set; }
        public string AreaOfPracticeEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistAreaOfPractice> TherapistAreaOfPractices { get; set; }
    }
}
