//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetListClientForClientRequestPage_Result
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Region { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Message { get; set; }
        public string DeletedAdditionalNotes { get; set; }
        public int RegionId { get; set; }
        public string consultationReason { get; set; }
        public string DeleteReason { get; set; }
        public string RequestStatus { get; set; }
        public string LastTherapistMessage { get; set; }
        public Nullable<int> RefusedCount { get; set; }
    }
}
