//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetClientSentToExternalAssociationCount_Result
    {
        public Nullable<int> TotalResult { get; set; }
        public Nullable<int> NotDefinedCount { get; set; }
        public Nullable<int> TookInChargeCount { get; set; }
        public Nullable<int> NotTookInChargeCount { get; set; }
    }
}
