//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapistBill
    {
        public int Id { get; set; }
        public int TherapistId { get; set; }
        public int BillNumber { get; set; }
        public System.DateTime Date { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TpsAmount { get; set; }
        public decimal TvqAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Therapist Therapists { get; set; }
    }
}
