//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Therapist()
        {
            this.TherapistAreaOfPractices = new HashSet<TherapistAreaOfPractice>();
            this.TherapistAssociationAndProfessionalOrders = new HashSet<TherapistAssociationAndProfessionalOrder>();
            this.TherapistAvailabilities = new HashSet<TherapistAvailability>();
            this.TherapistClientAgeRanges = new HashSet<TherapistClientAgeRange>();
            this.TherapistClientTypes = new HashSet<TherapistClientType>();
            this.TherapistConsultationTypes = new HashSet<TherapistConsultationType>();
            this.TherapistLanguages = new HashSet<TherapistLanguage>();
            this.TherapistOfferedServices = new HashSet<TherapistOfferedService>();
            this.TherapistProfessionalTitles = new HashSet<TherapistProfessionalTitle>();
            this.TherapistSpecificSkills = new HashSet<TherapistSpecificSkill>();
            this.TherapistTheoreticalOrientations = new HashSet<TherapistTheoreticalOrientation>();
            this.TherapistInfo = new HashSet<TherapistInfo>();
            this.Clients = new HashSet<Clients>();
            this.TherapistClientRequest = new HashSet<TherapistClientRequest>();
            this.TherapistBill = new HashSet<TherapistBill>();
            this.ClientAppointments = new HashSet<ClientAppointments>();
            this.TherapistPayInformations = new HashSet<TherapistPayInformations>();
        }
    
        public int Id { get; set; }
        public System.DateTime HiringDate { get; set; }
        public Nullable<int> MaxWeeklyRequest { get; set; }
        public string AdminNotes { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistAreaOfPractice> TherapistAreaOfPractices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistAssociationAndProfessionalOrder> TherapistAssociationAndProfessionalOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistAvailability> TherapistAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistClientAgeRange> TherapistClientAgeRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistClientType> TherapistClientTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistConsultationType> TherapistConsultationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistLanguage> TherapistLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistOfferedService> TherapistOfferedServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistProfessionalTitle> TherapistProfessionalTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistSpecificSkill> TherapistSpecificSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistTheoreticalOrientation> TherapistTheoreticalOrientations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistInfo> TherapistInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistClientRequest> TherapistClientRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistBill> TherapistBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAppointments> ClientAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistPayInformations> TherapistPayInformations { get; set; }
    }
}
