//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerRunner.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceServerRunner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceServerRunner() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerRunner.Resources.ResourceServerRunner", typeof(ResourceServerRunner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Vous avez un rendez-vous avec votre thérapeute le {0} à {1}.&lt;br/&gt;Votre rendez-vous se tiendra au {2}.&lt;br/&gt;Vous pouvez payer votre rendez-vous à l&apos;adresse suivante : {3}&lt;br/&gt;Merci et au plaisir de vous voir bientôt!.
        /// </summary>
        public static string AppointmentReminder_Content_InPerson {
            get {
                return ResourceManager.GetString("AppointmentReminder_Content_InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Vous avez un rendez-vous avec votre thérapeute le {0} à {1}.&lt;br/&gt;Votre rendez-vous se déroulera en ligne. Votre thérapeute vous transmettra les informations de connexion.&lt;br/&gt;Vous pouvez payer votre rendez-vous à l&apos;adresse suivante : {2}&lt;br/&gt;Nous serons heureux de vous voir bientôt pour cette consultation virtuelle!.
        /// </summary>
        public static string AppointmentReminder_Content_Online {
            get {
                return ResourceManager.GetString("AppointmentReminder_Content_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /fr/client/payment/.
        /// </summary>
        public static string AppointmentReminder_PaymentLink {
            get {
                return ResourceManager.GetString("AppointmentReminder_PaymentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre rendez-vous RéseauPsy le {0} à {1}.
        /// </summary>
        public static string AppointmentReminder_Subject {
            get {
                return ResourceManager.GetString("AppointmentReminder_Subject", resourceCulture);
            }
        }
    }
}
