//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetListTherapistBillPaymentForAdminExcel_Result
    {
        public int BillId { get; set; }
        public string TherapistName { get; set; }
        public int BillNumber { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TpsAmount { get; set; }
        public decimal TvqAmount { get; set; }
        public string TpsNumber { get; set; }
        public string TvqNumber { get; set; }
        public System.DateTime BillSendDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
