//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetClientListForTherapistClientListPage_Result
    {
        public int ClientId { get; set; }
        public Nullable<bool> IsExternalClient { get; set; }
        public string ClientName { get; set; }
    }
}
