//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseauPsy.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReseauPsy.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour, &lt;br/&gt;
        ///Votre rendez-vous du {0} à {1} a été modifié pour le {2} à {3}.&lt;br/&gt;
        ///Veuillez noter que votre rendez-vous aura lieu au {4}.&lt;br/&gt;
        ///Vous pouvez effectuer le paiement de votre consultation à l&apos;adresse suivante: {5}&lt;br/&gt;
        ///Merci et au plaisir de vous voir bientôt!.
        /// </summary>
        public static string AppointmentModified_Content_InPerson {
            get {
                return ResourceManager.GetString("AppointmentModified_Content_InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;
        ///Votre rendez-vous du {0} à {1} a été modifié pour le {2} à {3}.&lt;br/&gt;
        ///Veuillez noter que votre rendez-vous se déroulera en ligne. Votre thérapeute vous transmettra les informations de connexion.&lt;br/&gt;
        ///Vous pouvez effectuer le paiement de votre consultation à l&apos;adresse suivante: {4}&lt;br/&gt;
        ///Au plaisir de vous voir bientôt pour cette consultation virtuelle!.
        /// </summary>
        public static string AppointmentModified_Content_Online {
            get {
                return ResourceManager.GetString("AppointmentModified_Content_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre rendez-vous RéseauPsy a été modifié.
        /// </summary>
        public static string AppointmentModified_Subject {
            get {
                return ResourceManager.GetString("AppointmentModified_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Vous pouvez payer votre rendez-vous à l&apos;adresse suivante : {0}&lt;br/&gt;Au plaisir de vous voir bientôt!.
        /// </summary>
        public static string AppointmentNeedPayment_Content {
            get {
                return ResourceManager.GetString("AppointmentNeedPayment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de paiement de votre rendez-vous..
        /// </summary>
        public static string AppointmentNeedPayment_Manual_Subject {
            get {
                return ResourceManager.GetString("AppointmentNeedPayment_Manual_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Notre système de gestion des rendez-vous nous indique que vous n&apos;avez pas payé votre rendez-vous du {0}.&lt;br/&gt;Vous pouvez effectuer votre paiement en cliquant sur ce lien : {1}.&lt;br/&gt; Message de votre thérapeute : {2}.
        /// </summary>
        public static string AppointmentNeedPayment_Manuel_Content {
            get {
                return ResourceManager.GetString("AppointmentNeedPayment_Manuel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre rendez-vous Réseau Psy requiert un paiement.
        /// </summary>
        public static string AppointmentNeedPayment_Subject {
            get {
                return ResourceManager.GetString("AppointmentNeedPayment_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Suite à votre demande, votre requête pour une consultation a été supprimée. Nous vous invitons à entrer de nouveau en contact avec nous au besoin.&lt;br/&gt;Merci!.
        /// </summary>
        public static string AppointmentRequestDeleted_Content {
            get {
                return ResourceManager.GetString("AppointmentRequestDeleted_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande de consultation RéseauPsy .
        /// </summary>
        public static string AppointmentRequestDeleted_Subject {
            get {
                return ResourceManager.GetString("AppointmentRequestDeleted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Votre rendez-vous pré-payé RéseauPsy a été annulé. Notre système a donc procédé au remboursement automatique du paiement de votre consultation.&lt;br/&gt;Merci!.
        /// </summary>
        public static string ChargeCancelled_Content {
            get {
                return ResourceManager.GetString("ChargeCancelled_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre paiement pré-autorisé RéseauPsy..
        /// </summary>
        public static string ChargeCancelled_Subject {
            get {
                return ResourceManager.GetString("ChargeCancelled_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Voici les informations de connexion pour votre compte thérapeute RéseauPsy :&lt;br/&gt; URL : {0}&lt;br/&gt;Nom d&apos;utilisateur : {1}&lt;br/&gt;Mot de passe : {2}.
        /// </summary>
        public static string CreateTherapist_Content {
            get {
                return ResourceManager.GetString("CreateTherapist_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de votre compte thérapeute RéseauPsy.
        /// </summary>
        public static string CreateTherapist_Subject {
            get {
                return ResourceManager.GetString("CreateTherapist_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du client : {0}&lt;br/&gt;
        ///Courriel : {1}&lt;br /&gt;
        ///Numéro de téléphone : {2}&lt;br /&gt;
        ///Ville : {3}&lt;br /&gt;
        ///Région : {4}&lt;br /&gt;
        ///Code postal : {5}&lt;br /&gt;
        ///Raison de la consultation : {6}&lt;br /&gt;
        ///Âge du client : {7}&lt;br /&gt;
        ///{8}
        ///Date de la demande du client : {9}&lt;br/&gt;
        ///{10}
        ///{11}.
        /// </summary>
        public static string ExternalAssociationSend_Content {
            get {
                return ResourceManager.GetString("ExternalAssociationSend_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note supplémentaire de RéseauPsy : {0}&lt;br /&gt;.
        /// </summary>
        public static string ExternalAssociationSend_PartialAdminNote {
            get {
                return ResourceManager.GetString("ExternalAssociationSend_PartialAdminNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message supplémentaire du client : {0}&lt;br /&gt;.
        /// </summary>
        public static string ExternalAssociationSend_PartialClientMessage {
            get {
                return ResourceManager.GetString("ExternalAssociationSend_PartialClientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence client de RéseauPsy.
        /// </summary>
        public static string ExternalAssociationSend_Subject {
            get {
                return ResourceManager.GetString("ExternalAssociationSend_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Vous pouvez télécharger votre reçu numérique ici : {0}&lt;br /&gt;Merci!.
        /// </summary>
        public static string ReceiptReady_Content {
            get {
                return ResourceManager.GetString("ReceiptReady_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger votre reçu RéseauPsy.
        /// </summary>
        public static string ReceiptReady_Subject {
            get {
                return ResourceManager.GetString("ReceiptReady_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Vous pouvez télécharger votre reçu numérique RéseauPsy à l&apos;adresse suivante : {0}&lt;br /&gt;Merci!.
        /// </summary>
        public static string ResendReceipt_Content {
            get {
                return ResourceManager.GetString("ResendReceipt_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre reçu de rendez-vous chez RéseauPsy.
        /// </summary>
        public static string ResendReceipt_Subject {
            get {
                return ResourceManager.GetString("ResendReceipt_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;Votre lien sera valide pendant {0} heures.
        ///Vous pouvez réinitialiser votre mot de passe à l&apos;adresse suivante : {1}&lt;br/&gt;Merci!.
        /// </summary>
        public static string ResetPassword_Content {
            get {
                return ResourceManager.GetString("ResetPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisation de mot de passe.
        /// </summary>
        public static string ResetPassword_Subject {
            get {
                return ResourceManager.GetString("ResetPassword_Subject", resourceCulture);
            }
        }
    }
}
