//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseauPsy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReseauPsy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6277 rue D&apos;Iberville.
        /// </summary>
        public static string _Global_ReseauPsy_Adresse {
            get {
                return ResourceManager.GetString("_Global_ReseauPsy_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montréal (Québec) H2G2C5.
        /// </summary>
        public static string _Global_ReseauPsy_Adresse2 {
            get {
                return ResourceManager.GetString("_Global_ReseauPsy_Adresse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RéseauPsy Inc..
        /// </summary>
        public static string _Global_ReseauPsy_Name {
            get {
                return ResourceManager.GetString("_Global_ReseauPsy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier des rendez-vous.
        /// </summary>
        public static string AdminCalendar_H1 {
            get {
                return ResourceManager.GetString("AdminCalendar_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier des rendez-vous.
        /// </summary>
        public static string AdminCalendar_Title {
            get {
                return ResourceManager.GetString("AdminCalendar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous.
        /// </summary>
        public static string AdminDashboard_Appointments {
            get {
                return ResourceManager.GetString("AdminDashboard_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures.
        /// </summary>
        public static string AdminDashboard_Bill {
            get {
                return ResourceManager.GetString("AdminDashboard_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation.
        /// </summary>
        public static string AdminDashboard_Consultation {
            get {
                return ResourceManager.GetString("AdminDashboard_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string AdminDashboard_H1 {
            get {
                return ResourceManager.GetString("AdminDashboard_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string AdminDashboard_Title {
            get {
                return ResourceManager.GetString("AdminDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande(s) à traiter.
        /// </summary>
        public static string AdminDashboard_Todo {
            get {
                return ResourceManager.GetString("AdminDashboard_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture(s) à payer.
        /// </summary>
        public static string AdminDashboard_ToPay {
            get {
                return ResourceManager.GetString("AdminDashboard_ToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous cette semaine.
        /// </summary>
        public static string AdminDashboard_WeeklyAppointment {
            get {
                return ResourceManager.GetString("AdminDashboard_WeeklyAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la création de l&apos;administrateur.
        /// </summary>
        public static string AdminDetail_CreateError {
            get {
                return ResourceManager.GetString("AdminDetail_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;administrateur a été créé avec succès.
        /// </summary>
        public static string AdminDetail_CreateSuccess {
            get {
                return ResourceManager.GetString("AdminDetail_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la modification de l&apos;administrateur.
        /// </summary>
        public static string AdminDetail_EditError {
            get {
                return ResourceManager.GetString("AdminDetail_EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;administrateur a été modifié avec succès.
        /// </summary>
        public static string AdminDetail_EditSuccess {
            get {
                return ResourceManager.GetString("AdminDetail_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail d&apos;un administrateur.
        /// </summary>
        public static string AdminDetail_H1 {
            get {
                return ResourceManager.GetString("AdminDetail_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez laisser les champs de mot de passe vides si vous ne voulez pas changer le mot de passe.
        /// </summary>
        public static string AdminDetail_LeavePasswordEmpty {
            get {
                return ResourceManager.GetString("AdminDetail_LeavePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails d&apos;un administrateur.
        /// </summary>
        public static string AdminDetail_Title {
            get {
                return ResourceManager.GetString("AdminDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir supprimer{0}?.
        /// </summary>
        public static string AdminList_DeleteModal_Text {
            get {
                return ResourceManager.GetString("AdminList_DeleteModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression.
        /// </summary>
        public static string AdminList_DeleteModal_Title {
            get {
                return ResourceManager.GetString("AdminList_DeleteModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des administrateurs.
        /// </summary>
        public static string AdminList_H1 {
            get {
                return ResourceManager.GetString("AdminList_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir restaurer{0}?.
        /// </summary>
        public static string AdminList_RestaureModal_Text {
            get {
                return ResourceManager.GetString("AdminList_RestaureModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la restauration.
        /// </summary>
        public static string AdminList_RestaureModal_Title {
            get {
                return ResourceManager.GetString("AdminList_RestaureModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des administrateurs.
        /// </summary>
        public static string AdminList_Title {
            get {
                return ResourceManager.GetString("AdminList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas modifier la durée de ce rendez-vous, car le client a déjà reçu le lien de paiement..
        /// </summary>
        public static string Appointment_CantResize {
            get {
                return ResourceManager.GetString("Appointment_CantResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous.
        /// </summary>
        public static string AppointmentList_ExcelDocument_TabName {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocument_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_Client {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_Date {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de réclamation.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_ReclamationStatus {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_ReclamationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_Status {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thérapeute.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_Therapist {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_Therapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure.
        /// </summary>
        public static string AppointmentList_ExcelDocumentTableHeader_Time {
            get {
                return ResourceManager.GetString("AppointmentList_ExcelDocumentTableHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de rendez-vous.
        /// </summary>
        public static string AppointmentList_H1 {
            get {
                return ResourceManager.GetString("AppointmentList_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réclamé.
        /// </summary>
        public static string AppointmentList_ReclamationStatus_Claimed {
            get {
                return ResourceManager.GetString("AppointmentList_ReclamationStatus_Claimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non réclamé.
        /// </summary>
        public static string AppointmentList_ReclamationStatus_NotClaimed {
            get {
                return ResourceManager.GetString("AppointmentList_ReclamationStatus_NotClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payé.
        /// </summary>
        public static string AppointmentList_ReclamationStatus_Payed {
            get {
                return ResourceManager.GetString("AppointmentList_ReclamationStatus_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de rendez-vous.
        /// </summary>
        public static string AppointmentList_Title {
            get {
                return ResourceManager.GetString("AppointmentList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les rendez-vous ont été payés..
        /// </summary>
        public static string AppointmentNotPayed_AllPayed {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_AllPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer un rendez-vous non payé. Assurez-vous de supprimer uniquement les mauvaises créances. Une fois supprimé, un rendez-vous ne pourra plus être payé..
        /// </summary>
        public static string AppointmentNotPayed_DeleteModal_Text {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_DeleteModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise créance.
        /// </summary>
        public static string AppointmentNotPayed_DeleteModal_Title {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_DeleteModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous non payés.
        /// </summary>
        public static string AppointmentNotPayed_H1 {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce formulaire permet de renvoyer un courriel au client contenant un lien afin de compléter le paiement. Vous pouvez ajouter un message personnalisé. Le lien sera automatiquement inclus dans le courriel..
        /// </summary>
        public static string AppointmentNotPayed_SendModal_Text {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_SendModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renvoyer le lien de paiement.
        /// </summary>
        public static string AppointmentNotPayed_SendModal_Title {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_SendModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le courriel a été envoyé avec succès..
        /// </summary>
        public static string AppointmentNotPayed_Success {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tableau ci-dessous affiche les rendez-vous non payés. Les rendez-vous disparaîtront de cette liste lorsque les clients les auront payés. Vous pourrez ensuite les réclamer à RéseauPsy..
        /// </summary>
        public static string AppointmentNotPayed_Text {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous non payés.
        /// </summary>
        public static string AppointmentNotPayed_Title {
            get {
                return ResourceManager.GetString("AppointmentNotPayed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note pour l&apos;association externe.
        /// </summary>
        public static string AppointmentRequest_AssignModal_NoteForAssociation {
            get {
                return ResourceManager.GetString("AppointmentRequest_AssignModal_NoteForAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note pour le thérapeute.
        /// </summary>
        public static string AppointmentRequest_AssignModal_NoteForTherapist {
            get {
                return ResourceManager.GetString("AppointmentRequest_AssignModal_NoteForTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message du thérapeute.
        /// </summary>
        public static string AppointmentRequest_AssignModal_ReturnMessage {
            get {
                return ResourceManager.GetString("AppointmentRequest_AssignModal_ReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribuer la demande de consultation.
        /// </summary>
        public static string AppointmentRequest_AssignModal_Title {
            get {
                return ResourceManager.GetString("AppointmentRequest_AssignModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison de la suppression.
        /// </summary>
        public static string AppointmentRequest_DeleteModal_Reason {
            get {
                return ResourceManager.GetString("AppointmentRequest_DeleteModal_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir supprimer cette demande de consultation?.
        /// </summary>
        public static string AppointmentRequest_DeleteModal_Text {
            get {
                return ResourceManager.GetString("AppointmentRequest_DeleteModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression.
        /// </summary>
        public static string AppointmentRequest_DeleteModal_Title {
            get {
                return ResourceManager.GetString("AppointmentRequest_DeleteModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de rendez-vous.
        /// </summary>
        public static string AppointmentRequest_H1 {
            get {
                return ResourceManager.GetString("AppointmentRequest_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison de la suppression.
        /// </summary>
        public static string AppointmentRequest_RestoreModal_Reason {
            get {
                return ResourceManager.GetString("AppointmentRequest_RestoreModal_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de restaurer une demande de consultation qui a été supprimée précédemment. Voulez-vous poursuivre?.
        /// </summary>
        public static string AppointmentRequest_RestoreModal_Text {
            get {
                return ResourceManager.GetString("AppointmentRequest_RestoreModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la restauration.
        /// </summary>
        public static string AppointmentRequest_RestoreModal_Title {
            get {
                return ResourceManager.GetString("AppointmentRequest_RestoreModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette demande de consultation a déjà été envoyée à un thérapeute et elle est en attente de confirmation. Si vous récupérez la demande, celle-ci disparaîtra de la liste de demandes en attente du thérapeute. Êtes-vous sûr de vouloir poursuivre?.
        /// </summary>
        public static string AppointmentRequest_RetreiveModal_Text {
            get {
                return ResourceManager.GetString("AppointmentRequest_RetreiveModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la récupération.
        /// </summary>
        public static string AppointmentRequest_RetreiveModal_Title {
            get {
                return ResourceManager.GetString("AppointmentRequest_RetreiveModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimé.
        /// </summary>
        public static string AppointmentRequest_Status_Deleted {
            get {
                return ResourceManager.GetString("AppointmentRequest_Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associé.
        /// </summary>
        public static string AppointmentRequest_Status_HasTherapist {
            get {
                return ResourceManager.GetString("AppointmentRequest_Status_HasTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non associé.
        /// </summary>
        public static string AppointmentRequest_Status_NoTherapist {
            get {
                return ResourceManager.GetString("AppointmentRequest_Status_NoTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association externe.
        /// </summary>
        public static string AppointmentRequest_Status_SentToExternalAssociation {
            get {
                return ResourceManager.GetString("AppointmentRequest_Status_SentToExternalAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente.
        /// </summary>
        public static string AppointmentRequest_Status_Waiting {
            get {
                return ResourceManager.GetString("AppointmentRequest_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de rendez-vous.
        /// </summary>
        public static string AppointmentRequest_Title {
            get {
                return ResourceManager.GetString("AppointmentRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe a été modifié avec succès.
        /// </summary>
        public static string ChangePassword_Confirmation {
            get {
                return ResourceManager.GetString("ChangePassword_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe actuel n&apos;est pas valide.
        /// </summary>
        public static string ChangePassword_Error_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePassword_Error_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon mot de passe.
        /// </summary>
        public static string ChangePassword_H1 {
            get {
                return ResourceManager.GetString("ChangePassword_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon mot de passe.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures envoyées.
        /// </summary>
        public static string ClaimForm_BillSent {
            get {
                return ResourceManager.GetString("ClaimForm_BillSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non payé.
        /// </summary>
        public static string ClaimForm_BillSentTableStatus_NotPayed {
            get {
                return ResourceManager.GetString("ClaimForm_BillSentTableStatus_NotPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payé.
        /// </summary>
        public static string ClaimForm_BillSentTableStatus_Payed {
            get {
                return ResourceManager.GetString("ClaimForm_BillSentTableStatus_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réclamer les rendez-vous.
        /// </summary>
        public static string ClaimForm_ClaimAppointment {
            get {
                return ResourceManager.GetString("ClaimForm_ClaimAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures.
        /// </summary>
        public static string ClaimForm_ExcelDocument_TabName {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocument_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_Amount {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de facture.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_BillNumber {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;envoi.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_DateSent {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de paiement.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_PaymentStatus {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPS.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_Tps {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_Tps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVQ.
        /// </summary>
        public static string ClaimForm_ExcelDocumentTableHeader_Tvq {
            get {
                return ResourceManager.GetString("ClaimForm_ExcelDocumentTableHeader_Tvq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous réclamable.
        /// </summary>
        public static string ClaimForm_H1 {
            get {
                return ResourceManager.GetString("ClaimForm_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas de rendez-vous réclamable.
        /// </summary>
        public static string ClaimForm_NoClaimmable {
            get {
                return ResourceManager.GetString("ClaimForm_NoClaimmable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévisualiser la facture.
        /// </summary>
        public static string ClaimForm_PreviewModal_Title {
            get {
                return ResourceManager.GetString("ClaimForm_PreviewModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les rendez-vous dans le tableau ci-dessous sont prêts à être réclamés à l&apos;Administration. Pour apparaître dans les tableaux ci-dessous, les présences doivent avoir été confirmées et les rendez-vous doivent avoir été payés..
        /// </summary>
        public static string ClaimForm_Text {
            get {
                return ResourceManager.GetString("ClaimForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous réclamable.
        /// </summary>
        public static string ClaimForm_Title {
            get {
                return ResourceManager.GetString("ClaimForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string ClientListAdmin_H1 {
            get {
                return ResourceManager.GetString("ClientListAdmin_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string ClientListTherapist_H1 {
            get {
                return ResourceManager.GetString("ClientListTherapist_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de client.
        /// </summary>
        public static string ClientListTherapist_Label_ClientType {
            get {
                return ResourceManager.GetString("ClientListTherapist_Label_ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir supprimer ce client?.
        /// </summary>
        public static string ClientListTherapist_ModalDelete_Text {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supression de client.
        /// </summary>
        public static string ClientListTherapist_ModalDelete_Title {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir restaurer ce client?.
        /// </summary>
        public static string ClientListTherapist_ModalRestore_Text {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalRestore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauration de client.
        /// </summary>
        public static string ClientListTherapist_ModalRestore_Title {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalRestore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe.
        /// </summary>
        public static string ClientListTherapist_Option_ExternalClient {
            get {
                return ResourceManager.GetString("ClientListTherapist_Option_ExternalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interne.
        /// </summary>
        public static string ClientListTherapist_Option_InternalClient {
            get {
                return ResourceManager.GetString("ClientListTherapist_Option_InternalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_AppointmentType {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_ClientName {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de consultation.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_ConsultationType {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_ConsultationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_Date {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Reçu.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_ReceiptNumber {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-total.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_SubTotal {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reçu client.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_TabName {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thérapeute.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_Therapist {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_Therapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_Total {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPS.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_Tps {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_Tps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVQ.
        /// </summary>
        public static string ClientReceipt_ExcelDocument_Tvq {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocument_Tvq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} en {1}.
        /// </summary>
        public static string ClientReceipt_ExcelDocumentRow_AppointmentType {
            get {
                return ResourceManager.GetString("ClientReceipt_ExcelDocumentRow_AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frais administratif pour absence.
        /// </summary>
        public static string ClientReceiptPdf_Label_AdministrativeCharges {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Label_AdministrativeCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de rendez-vous.
        /// </summary>
        public static string ClientReceiptPdf_Label_AppointmentDate {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Label_AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reçu pour assurances.
        /// </summary>
        public static string ClientReceiptPdf_Label_ReciptForInsurance {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Label_ReciptForInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assuré par.
        /// </summary>
        public static string ClientReceiptPdf_Label_TherapistName {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Label_TherapistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre(s) du thérapeute.
        /// </summary>
        public static string ClientReceiptPdf_Label_TherapistTitle {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Label_TherapistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} en {1}.
        /// </summary>
        public static string ClientReceiptPdf_Name_AppointmentType {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Name_AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les rendez-vous ont été confirmés.
        /// </summary>
        public static string ConfirmPresence_AllConfirmedMessage {
            get {
                return ResourceManager.GetString("ConfirmPresence_AllConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présence à confirmer.
        /// </summary>
        public static string ConfirmPresence_H1 {
            get {
                return ResourceManager.GetString("ConfirmPresence_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doit-on appliquer des frais d&apos;administration pour annulation tardive?.
        /// </summary>
        public static string ConfirmPresence_ModalAnnulationFees_Message {
            get {
                return ResourceManager.GetString("ConfirmPresence_ModalAnnulationFees_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frais d&apos;annulation.
        /// </summary>
        public static string ConfirmPresence_ModalAnnulationFees_Title {
            get {
                return ResourceManager.GetString("ConfirmPresence_ModalAnnulationFees_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la présence.
        /// </summary>
        public static string ConfirmPresence_PresenceToConfirm {
            get {
                return ResourceManager.GetString("ConfirmPresence_PresenceToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présence à confirmer.
        /// </summary>
        public static string ConfirmPresence_Title {
            get {
                return ResourceManager.GetString("ConfirmPresence_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La présence à été confirmée!.
        /// </summary>
        public static string ConfirmPresence_ToastrSuccess_Message {
            get {
                return ResourceManager.GetString("ConfirmPresence_ToastrSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création d&apos;un client.
        /// </summary>
        public static string DetailClientAdmin_H1_CreateClient {
            get {
                return ResourceManager.GetString("DetailClientAdmin_H1_CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;un client.
        /// </summary>
        public static string DetailClientAdmin_H1_EditClient {
            get {
                return ResourceManager.GetString("DetailClientAdmin_H1_EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de communication.
        /// </summary>
        public static string DetailClientAdmin_Label_CommunicationLanguage {
            get {
                return ResourceManager.GetString("DetailClientAdmin_Label_CommunicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison de consultation.
        /// </summary>
        public static string DetailClientAdmin_Label_ConsultationReason {
            get {
                return ResourceManager.GetString("DetailClientAdmin_Label_ConsultationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser des tarifs horaires personnalisés.
        /// </summary>
        public static string DetailClientAdmin_Label_UseCustomRate {
            get {
                return ResourceManager.GetString("DetailClientAdmin_Label_UseCustomRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création du client s&apos;est faite avec succès.
        /// </summary>
        public static string DetailClientAdmin_SucceededCreated {
            get {
                return ResourceManager.GetString("DetailClientAdmin_SucceededCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La modification du client s&apos;est faite avec succès.
        /// </summary>
        public static string DetailClientAdmin_SucceededEdited {
            get {
                return ResourceManager.GetString("DetailClientAdmin_SucceededEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un thérapeute.
        /// </summary>
        public static string DetailsTherapist_CreateTherapist {
            get {
                return ResourceManager.GetString("DetailsTherapist_CreateTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un thérapeute.
        /// </summary>
        public static string DetailsTherapist_EditTherapist {
            get {
                return ResourceManager.GetString("DetailsTherapist_EditTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenez-vous des clients venant des compagnies d&apos;assurances?.
        /// </summary>
        public static string DetailTherapist_ClientFromInsurance {
            get {
                return ResourceManager.GetString("DetailTherapist_ClientFromInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenez-vous des clients venant des tiers payeurs tels que la CSST, l&apos;IVAC ou le CAVAC?.
        /// </summary>
        public static string DetailTherapist_ClientFromThirdParty {
            get {
                return ResourceManager.GetString("DetailTherapist_ClientFromThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous intéressé à suivre des formations supplémentaires offertes par RéseauPsy?.
        /// </summary>
        public static string DetailTherapist_InterestedInFormation {
            get {
                return ResourceManager.GetString("DetailTherapist_InterestedInFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandes maximales par semaine.
        /// </summary>
        public static string DetailTherapist_MaxRequest {
            get {
                return ResourceManager.GetString("DetailTherapist_MaxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le thérapeute à été créé avec succès..
        /// </summary>
        public static string DetailTherapist_SuccedeedCreated {
            get {
                return ResourceManager.GetString("DetailTherapist_SuccedeedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le thérapeute à été modifié avec succès..
        /// </summary>
        public static string DetailTherapist_SuccedeedModified {
            get {
                return ResourceManager.GetString("DetailTherapist_SuccedeedModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails d&apos;un thérapeute.
        /// </summary>
        public static string DetailTherapist_Title {
            get {
                return ResourceManager.GetString("DetailTherapist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le statut.
        /// </summary>
        public static string ExternalAssociation_ChangeStatus {
            get {
                return ResourceManager.GetString("ExternalAssociation_ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ExternalAssociation_ExcelDocument_TabName {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocument_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string ExternalAssociation_ExcelDocumentTableHeader_Association {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocumentTableHeader_Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string ExternalAssociation_ExcelDocumentTableHeader_Client {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocumentTableHeader_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;envoi.
        /// </summary>
        public static string ExternalAssociation_ExcelDocumentTableHeader_SentDate {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocumentTableHeader_SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string ExternalAssociation_ExcelDocumentTableHeader_Status {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocumentTableHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de changement de statut.
        /// </summary>
        public static string ExternalAssociation_ExcelDocumentTableHeader_StatusChangedDate {
            get {
                return ResourceManager.GetString("ExternalAssociation_ExcelDocumentTableHeader_StatusChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations externes.
        /// </summary>
        public static string ExternalAssociation_H1 {
            get {
                return ResourceManager.GetString("ExternalAssociation_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations externes.
        /// </summary>
        public static string ExternalAssociation_Title {
            get {
                return ResourceManager.GetString("ExternalAssociation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié.
        /// </summary>
        public static string ForgotPassword_H1 {
            get {
                return ResourceManager.GetString("ForgotPassword_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la page de connexion.
        /// </summary>
        public static string ForgotPassword_ReturnToLogin {
            get {
                return ResourceManager.GetString("ForgotPassword_ReturnToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre adresse courriel afin de recevoir un lien pour réinitialiser votre mot de passe.
        /// </summary>
        public static string ForgotPassword_Subtitle {
            get {
                return ResourceManager.GetString("ForgotPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si le courriel correspond à un compte valide, un courriel vous a été acheminé afin de réinitialiser votre mot de passe.
        /// </summary>
        public static string ForgotPassword_Success_Message {
            get {
                return ResourceManager.GetString("ForgotPassword_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des reçus clients.
        /// </summary>
        public static string ListClientReceipt_H1 {
            get {
                return ResourceManager.GetString("ListClientReceipt_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez modifier l&apos;adresse courriel avant d&apos;envoyer le reçu de nouveau..
        /// </summary>
        public static string ListClientReceipt_ModalSend_Instruction {
            get {
                return ResourceManager.GetString("ListClientReceipt_ModalSend_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renvoyer le reçu.
        /// </summary>
        public static string ListClientReceipt_ModalSend_Title {
            get {
                return ResourceManager.GetString("ListClientReceipt_ModalSend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renvoyer le reçu.
        /// </summary>
        public static string ListClientReceipt_ResendReceipt {
            get {
                return ResourceManager.GetString("ListClientReceipt_ResendReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des reçus clients.
        /// </summary>
        public static string ListClientReceipt_Title {
            get {
                return ResourceManager.GetString("ListClientReceipt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le reçu à bien été envoyé!.
        /// </summary>
        public static string ListClientReceipt_Toastr_ResendConfirmation {
            get {
                return ResourceManager.GetString("ListClientReceipt_Toastr_ResendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte est verrouillé, car vous avez effectué trop de tentatives infructueuses. Utilisez le lien &apos;mot de passe oublié&apos; pour réinitialiser votre mot de passe..
        /// </summary>
        public static string Login_Error_AccountLocked {
            get {
                return ResourceManager.GetString("Login_Error_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre tentative de connexion à échoué. Veuillez réessayer..
        /// </summary>
        public static string Login_Error_ConnectionFailed {
            get {
                return ResourceManager.GetString("Login_Error_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour!.
        /// </summary>
        public static string Login_H1 {
            get {
                return ResourceManager.GetString("Login_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mémoriser mon mot de passe.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous pour accéder à votre tableau de bord.
        /// </summary>
        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenez-vous des clients venant des compagnies d&apos;assurances?.
        /// </summary>
        public static string MyProfil_ClientFromInsurance {
            get {
                return ResourceManager.GetString("MyProfil_ClientFromInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenez-vous des clients venant des tiers payeurs, tels que la CSST, l&apos;IVAC ou le CAVAC?.
        /// </summary>
        public static string MyProfil_ClientFromThirdParty {
            get {
                return ResourceManager.GetString("MyProfil_ClientFromThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aller au tableau de bord.
        /// </summary>
        public static string MyProfil_GoTODashboard {
            get {
                return ResourceManager.GetString("MyProfil_GoTODashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous intéressé à suivre des formations supplémentaires offertes par Réseau Psy?.
        /// </summary>
        public static string MyProfil_InterestedInFormation {
            get {
                return ResourceManager.GetString("MyProfil_InterestedInFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandes maximales par semaine.
        /// </summary>
        public static string MyProfil_MaxRequest {
            get {
                return ResourceManager.GetString("MyProfil_MaxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre profil a été modifié avec succès.
        /// </summary>
        public static string MyProfil_SuccessMessage {
            get {
                return ResourceManager.GetString("MyProfil_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        public static string MyProfile_H1 {
            get {
                return ResourceManager.GetString("MyProfile_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre inscription est incomplète. Vous devez la terminer avant de pouvoir accéder aux autres sections du site..
        /// </summary>
        public static string MyProfile_Incomplete {
            get {
                return ResourceManager.GetString("MyProfile_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        public static string MyProfile_Title {
            get {
                return ResourceManager.GetString("MyProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes compétences.
        /// </summary>
        public static string MySkills_H1 {
            get {
                return ResourceManager.GetString("MySkills_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes compétences.
        /// </summary>
        public static string MySkills_Title {
            get {
                return ResourceManager.GetString("MySkills_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci! Votre rendez-vous à été pré-autorisé. Le paiement sera prélevé automatiquement lorsque votre thérapeute confirmera la présence à votre rendez-vous. Vous pourrez télécharger votre reçu une fois le paiement effectué..
        /// </summary>
        public static string Payment_PreAutorisation_Done {
            get {
                return ResourceManager.GetString("Payment_PreAutorisation_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Attention!&lt;/strong&gt; Puisque votre rendez-vous n&apos;a pas encore eu lieu, il s&apos;agit d&apos;une pré-autorisation. Le paiement sera fait automatiquement lorsque votre thérapeute confirmera votre rencontre..
        /// </summary>
        public static string Payment_PreAutorisation_Message {
            get {
                return ResourceManager.GetString("Payment_PreAutorisation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci! Votre rendez-vous à été payé. Vous pouvez télécharger votre reçu à l&apos;aide du bouton ci-dessous..
        /// </summary>
        public static string Payment_ReceiptAvailable {
            get {
                return ResourceManager.GetString("Payment_ReceiptAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paiement d&apos;un rendez-vous.
        /// </summary>
        public static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse que vous avez utilisée est invalide. Veuillez réessayer..
        /// </summary>
        public static string PaymentInvalid_Text {
            get {
                return ResourceManager.GetString("PaymentInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien de paiement invalide.
        /// </summary>
        public static string PaymentInvalid_Title {
            get {
                return ResourceManager.GetString("PaymentInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe n&apos;est pas assez sécuritaire. Il doit contenir :
        ///&lt;ul&gt;
        ///&lt;li&gt;Minimum d&apos;un chiffre&lt;/li&gt;
        ///&lt;li&gt;Un minimum de 6 caractères&lt;/li&gt;
        ///&lt;li&gt;Minimum d&apos;une lettre minuscule&lt;/li&gt;
        ///&lt;li&gt;Minimum d&apos;une lettre majuscule&lt;/li&gt;
        ///&lt;li&gt;Minimum d&apos;un caractère spécial&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ResetPassword_Error_Requirement {
            get {
                return ResourceManager.GetString("ResetPassword_Error_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la réinitialisation du mot de passe. Veuillez réessayer plus tard..
        /// </summary>
        public static string ResetPassword_ErrorMessage_FailedToReset {
            get {
                return ResourceManager.GetString("ResetPassword_ErrorMessage_FailedToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien est invalide.
        /// </summary>
        public static string ResetPassword_ErrorMessage_InvalidLink {
            get {
                return ResourceManager.GetString("ResetPassword_ErrorMessage_InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien est expiré.
        /// </summary>
        public static string ResetPassword_ErrorMessage_LinkExpired {
            get {
                return ResourceManager.GetString("ResetPassword_ErrorMessage_LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a déjà été utilisé.
        /// </summary>
        public static string ResetPassword_ErrorMessage_LinkUsed {
            get {
                return ResourceManager.GetString("ResetPassword_ErrorMessage_LinkUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser votre mot de passe.
        /// </summary>
        public static string ResetPassword_H1 {
            get {
                return ResourceManager.GetString("ResetPassword_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemander un lien.
        /// </summary>
        public static string ResetPassword_ResendLink {
            get {
                return ResourceManager.GetString("ResetPassword_ResendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe du compte associé à cette adresse courriel a été réinitialisé avec succès..
        /// </summary>
        public static string ResetPassword_SuccessMessage_PasswordReseted {
            get {
                return ResourceManager.GetString("ResetPassword_SuccessMessage_PasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser votre mot de passe.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string Statistics_H1 {
            get {
                return ResourceManager.GetString("Statistics_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulation.
        /// </summary>
        public static string Statistics_H2_Cancelation {
            get {
                return ResourceManager.GetString("Statistics_H2_Cancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string Statistics_H2_Conversion {
            get {
                return ResourceManager.GetString("Statistics_H2_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous.
        /// </summary>
        public static string TherapistApointment_ModalAppointment_Title {
            get {
                return ResourceManager.GetString("TherapistApointment_ModalAppointment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous.
        /// </summary>
        public static string TherapistAppointment_H1 {
            get {
                return ResourceManager.GetString("TherapistAppointment_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de consultation à fixer.
        /// </summary>
        public static string TherapistAppointment_Instruction {
            get {
                return ResourceManager.GetString("TherapistAppointment_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce rendez-vous fait partie d&apos;une série de rendez-vous. Voulez-vous modifier tous les futurs rendez-vous ou celui-ci seulement?.
        /// </summary>
        public static string TherapistAppointment_ModalApplyFor_Text {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalApplyFor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer la modification.
        /// </summary>
        public static string TherapistAppointment_ModalApplyFor_Title {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalApplyFor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une répétition.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_AddRepetition {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_AddRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler ce rendez-vous.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_Cancel {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se termine après.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_EndAfter {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une séance = 1 heure.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_InfoBubble {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_InfoBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter le.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_RepeatDay {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_RepeatDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter tou(te)s les.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_RepeatEvery {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options de répétition.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_RepetitionOptions {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_RepetitionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner le client à l&apos;Administration.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_Return {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, vous devrez communiquer le lien de la visioconférence au client par vous même!.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_SendLink {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence à partir du.
        /// </summary>
        public static string TherapistAppointment_ModalAppointment_StartFrom {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalAppointment_StartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les rendez-vous de la série de consultations.
        /// </summary>
        public static string TherapistAppointment_ModalDelete_AllAppointment {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalDelete_AllAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Si vous voulez appliquer des frais administratifs au rendez-vous, vous devez garder ce rendez-vous et appliquer les frais dans la page de confirmation de présence.
        /// </summary>
        public static string TherapistAppointment_ModalDelete_DeleteInfo {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalDelete_DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier la raison pour laquelle vous désirez supprimer le rendez-vous..
        /// </summary>
        public static string TherapistAppointment_ModalDelete_Text {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression.
        /// </summary>
        public static string TherapistAppointment_ModalDelete_Title {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de référer le client à l&apos;Administration. Vous ne serez plus en mesure de consulter les informations le concernant, ni de fixer un rendez-vous avec lui. Veuillez spécifier pourquoi vous référez ce client à l&apos;Administration..
        /// </summary>
        public static string TherapistAppointment_ModalReturn_Text {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalReturn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référer à l&apos;Administration.
        /// </summary>
        public static string TherapistAppointment_ModalReturn_Title {
            get {
                return ResourceManager.GetString("TherapistAppointment_ModalReturn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous.
        /// </summary>
        public static string TherapistAppointment_Title {
            get {
                return ResourceManager.GetString("TherapistAppointment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_Bill_TabName {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_Bill_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de facture.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_BillNumber {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date du paiement de la facture.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_BillPaymentDate {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_BillPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de l&apos;envoi de la facture.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_BillSentDate {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_BillSentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paiements.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_Payment_TabName {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_Payment_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-total.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_SubTotal {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thérapeute.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TherapistName {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TherapistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de TPS.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TherapistTpsNumber {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TherapistTpsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de TVQ.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TherapistTvqNumber {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TherapistTvqNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant total.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TotalBill {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TotalBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant de la TPS.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TpsAmount {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TpsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant de la TVQ.
        /// </summary>
        public static string TherapistBill_ExcelDocumentTableHeader_TvqAmount {
            get {
                return ResourceManager.GetString("TherapistBill_ExcelDocumentTableHeader_TvqAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures thérapeute.
        /// </summary>
        public static string TherapistBill_H1 {
            get {
                return ResourceManager.GetString("TherapistBill_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;exportation.
        /// </summary>
        public static string TherapistBill_ModalExport_ExportationType {
            get {
                return ResourceManager.GetString("TherapistBill_ModalExport_ExportationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail d&apos;exportation.
        /// </summary>
        public static string TherapistBill_ModalExport_Title {
            get {
                return ResourceManager.GetString("TherapistBill_ModalExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer la date à laquelle vous avez procédé au paiement de la facture..
        /// </summary>
        public static string TherapistBill_ModalPay_Instruction {
            get {
                return ResourceManager.GetString("TherapistBill_ModalPay_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le paiement.
        /// </summary>
        public static string TherapistBill_ModalPay_Title {
            get {
                return ResourceManager.GetString("TherapistBill_ModalPay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures thérapeute.
        /// </summary>
        public static string TherapistBill_Title {
            get {
                return ResourceManager.GetString("TherapistBill_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturé à.
        /// </summary>
        public static string TherapistBillPdf_Label_BilledAt {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_BilledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture No..
        /// </summary>
        public static string TherapistBillPdf_Label_BillNumber {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture.
        /// </summary>
        public static string TherapistBillPdf_Label_BillTitle {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_BillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TherapistBillPdf_Label_DateTitle {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-total.
        /// </summary>
        public static string TherapistBillPdf_Label_Subtotal {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TherapistBillPdf_Label_Total {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string TherapistBillPdf_Th_Amount {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Th_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TherapistBillPdf_Th_Description {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Th_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux horaire.
        /// </summary>
        public static string TherapistBillPdf_Th_HourlyWage {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Th_HourlyWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string TherapistBillPdf_Th_Quantity {
            get {
                return ResourceManager.GetString("TherapistBillPdf_Th_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations du client.
        /// </summary>
        public static string TherapistClientRequest_ConsultModal_Title {
            get {
                return ResourceManager.GetString("TherapistClientRequest_ConsultModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les demandes suivantes vous ont été envoyées depuis l&apos;Administration. Vous devez les accepter ou les refuser en cliquant sur Consulter. Les demandes ne faisant l&apos;objet d&apos;aucune réponse avant la date d&apos;expiration seront automatiquement renvoyées à l&apos;Administration..
        /// </summary>
        public static string TherapistClientRequest_Text {
            get {
                return ResourceManager.GetString("TherapistClientRequest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandes en attente.
        /// </summary>
        public static string TherapistClientRequest_Title {
            get {
                return ResourceManager.GetString("TherapistClientRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accéder aux rendez-vous.
        /// </summary>
        public static string TherapistClientRequest_ToastrAccepted_Link {
            get {
                return ResourceManager.GetString("TherapistClientRequest_ToastrAccepted_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez maintenant fixer un rendez-vous dans la page des rendez-vous..
        /// </summary>
        public static string TherapistClientRequest_ToastrAccepted_Message {
            get {
                return ResourceManager.GetString("TherapistClientRequest_ToastrAccepted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande a été référée à l&apos;Administration.
        /// </summary>
        public static string TherapistClientRequest_ToastrRefused_Message {
            get {
                return ResourceManager.GetString("TherapistClientRequest_ToastrRefused_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string TherapistDashBoard_H1 {
            get {
                return ResourceManager.GetString("TherapistDashBoard_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir tous les rendez-vous.
        /// </summary>
        public static string TherapistDashBoard_SeeAll {
            get {
                return ResourceManager.GetString("TherapistDashBoard_SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string TherapistDashBoard_Title {
            get {
                return ResourceManager.GetString("TherapistDashBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des thérapeutes.
        /// </summary>
        public static string TherapistList_H1 {
            get {
                return ResourceManager.GetString("TherapistList_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir supprimer{0}?.
        /// </summary>
        public static string TherapistList_Modal_Delete_Text {
            get {
                return ResourceManager.GetString("TherapistList_Modal_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression.
        /// </summary>
        public static string TherapistList_ModalDelete_Title {
            get {
                return ResourceManager.GetString("TherapistList_ModalDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir restaurer{0}?.
        /// </summary>
        public static string TherapistList_ModalRestore_Text {
            get {
                return ResourceManager.GetString("TherapistList_ModalRestore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la restauration.
        /// </summary>
        public static string TherapistList_ModalRestore_Title {
            get {
                return ResourceManager.GetString("TherapistList_ModalRestore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune disponibilité.
        /// </summary>
        public static string TherapistList_Multiselect_NoAvailability {
            get {
                return ResourceManager.GetString("TherapistList_Multiselect_NoAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun service.
        /// </summary>
        public static string TherapistList_Multiselect_NoService {
            get {
                return ResourceManager.GetString("TherapistList_Multiselect_NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disponibilités sélectionnées.
        /// </summary>
        public static string TherapistList_Multiselect_SelectedAvailability {
            get {
                return ResourceManager.GetString("TherapistList_Multiselect_SelectedAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} services sélectionnés.
        /// </summary>
        public static string TherapistList_Multiselect_SelectedService {
            get {
                return ResourceManager.GetString("TherapistList_Multiselect_SelectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des thérapeutes.
        /// </summary>
        public static string TherapistList_Title {
            get {
                return ResourceManager.GetString("TherapistList_Title", resourceCulture);
            }
        }
    }
}
