//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    
    public partial class GetClaimableAmountForOneAppointment_Result
    {
        public Nullable<decimal> ClaimableAmount { get; set; }
        public Nullable<decimal> TpsAmount { get; set; }
        public Nullable<decimal> TvqAmount { get; set; }
    }
}
