//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseauPsy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTemp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTemp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReseauPsy.Resources.ResourceTemp", typeof(ResourceTemp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string ClientListAdmin_H1 {
            get {
                return ResourceManager.GetString("ClientListAdmin_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string ClientListTherapist_H1 {
            get {
                return ResourceManager.GetString("ClientListTherapist_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de client.
        /// </summary>
        public static string ClientListTherapist_Label_ClientType {
            get {
                return ResourceManager.GetString("ClientListTherapist_Label_ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir supprimer ce client?.
        /// </summary>
        public static string ClientListTherapist_ModalDelete_Text {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supression de client.
        /// </summary>
        public static string ClientListTherapist_ModalDelete_Title {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir restaurer ce client?.
        /// </summary>
        public static string ClientListTherapist_ModalRestore_Text {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalRestore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauration de client.
        /// </summary>
        public static string ClientListTherapist_ModalRestore_Title {
            get {
                return ResourceManager.GetString("ClientListTherapist_ModalRestore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe.
        /// </summary>
        public static string ClientListTherapist_Option_ExternalClient {
            get {
                return ResourceManager.GetString("ClientListTherapist_Option_ExternalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interne.
        /// </summary>
        public static string ClientListTherapist_Option_InternalClient {
            get {
                return ResourceManager.GetString("ClientListTherapist_Option_InternalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} en {1}.
        /// </summary>
        public static string ClientReceiptPdf_Name_AppointmentType {
            get {
                return ResourceManager.GetString("ClientReceiptPdf_Name_AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création d&apos;un client.
        /// </summary>
        public static string DetailClientAdmin_H1_CreateClient {
            get {
                return ResourceManager.GetString("DetailClientAdmin_H1_CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;un client.
        /// </summary>
        public static string DetailClientAdmin_H1_EditClient {
            get {
                return ResourceManager.GetString("DetailClientAdmin_H1_EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de communication.
        /// </summary>
        public static string DetailClientAdmin_Label_CommunicationLanguage {
            get {
                return ResourceManager.GetString("DetailClientAdmin_Label_CommunicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison de consultation.
        /// </summary>
        public static string DetailClientAdmin_Label_ConsultationReason {
            get {
                return ResourceManager.GetString("DetailClientAdmin_Label_ConsultationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création du client s&apos;est faite avec succès.
        /// </summary>
        public static string DetailClientAdmin_SucceededCreated {
            get {
                return ResourceManager.GetString("DetailClientAdmin_SucceededCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La modification du client s&apos;est faite avec succès.
        /// </summary>
        public static string DetailClientAdmin_SucceededEdited {
            get {
                return ResourceManager.GetString("DetailClientAdmin_SucceededEdited", resourceCulture);
            }
        }
    }
}
